name: Publish Status
on:
  workflow_dispatch:
    inputs:
      database:
        description: '读书 or ACGN'
        required: true
        default: 'ACGN'
      origin:
        description: 'link to source'
        required: true
      score:
        description: '1/2/3/4/5, required for ACGN, optional for 读书'
        required: false
      review:
        description: 'review, recommended for all'
        required: false
      status:
        description: '想读/在读/读过/放弃; required for 读书, ignored for ACGN'
        required: false
      category:
        description: 'recommeneded for 读书, ignored for ACGN'
        required: false
        default: 'Uncategorized'
      type:
        description: 'Anime/Light Novel/Manga/Game, recommeneded for ACGN, ignored for 读书'
        required: false
        default: 'Anime'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - run: node ./out/index.js
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          INPUT_DATABASE: ${{ github.event.inputs.database }}
          INPUT_ORIGIN: ${{ github.event.inputs.origin }}
          INPUT_SCORE: ${{ github.event.inputs.score }}
          INPUT_REVIEW: ${{ github.event.inputs.review }}
          INPUT_STATUS: ${{ github.event.inputs.status }}
          INPUT_CATEGORY: ${{ github.event.inputs.category }}
          INPUT_TYPE: ${{ github.event.inputs.type }}
