name: Publish Status
on:
  push:
    branches: [main]
    paths:
      - 'status.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - run: node ./out/index.js
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
